apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  
  labels:
    app: config-service
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service
          image: mostafadeghady/cofig-service
          imagePullPolicy: IfNotPresent
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: readiness-port
            failureThreshold: 30
            periodSeconds: 10
          
          ports:
            - containerPort: 8888
            - name: readiness-port
              containerPort: 8889


            
