apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service
  
  labels:
    app: edge-service
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: edge-service
  template:
    metadata:
      labels:
        app: edge-service
    spec:
      containers:
        - name: edge-service
          image: mostafadeghady/edge-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          env:
            - name: SPRING_REDIS_HOST
              value: polar-redis
            - name: ORDER_SERVICE_URL
              value: http://order-service:9002
            - name: CATALOG_SERVICE_URL
              value: http://catalog-service:9001
            - name: SPA_URL
              value: http://polar-ui:9004
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI
              value: http://polar-keycloak/realms/PolarBookshop
            
