apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  labels:
    app: catalog-service
spec:
  type: NodePort
  selector:
    app: catalog-service
  ports:
  - name: http 
    port: 80 
    nodePort: 30080
    targetPort: 9001